### ISSUE TITLE
Documentation: Google API asks "Which API?"

### ISSUE THREAD

**Issue by kjcole** [jonkensta/ibp#2]
In registering for Google API credentials, it asks me to enable the API I intend to use.  The README doesn't tell me which API I intend to use...  Specifically:

> _You need credentials to access APIs. [Enable the APIs you plan to use](https://console.developers.google.com/apis/library?project=dc-books-to-prisons-ibp&folder&organizationId) and then create the credentials they require. Depending on the API, you need an API key, a service account, or an OAuth 2.0 client ID. [Refer to the API documentation](https://support.google.com/googleapi/answer/6158857?hl=en_US) for details._

**Comment by jonkensta** [comment]
HI @kjcole, are you still interested in getting a demonstration of this working? If so, I can try to put something together for you.

**Comment by kjcole** [comment]
Hi @jonkensta. I will need to check back with the DC Books to Prisons people and see if they still want me to pursue this, I am thinking "probably not".
